// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import {gql, useMutation, useQuery, useSubscription} from "@apollo/client";
// import { Button } from '@audi/audi-ui-react';
// import { useState } from "react"

// const sub = gql`
//   subscription CounterChanged {
//     roomUpdated 
//   }
// `;

// const roomStateQuery = gql`
//     query GetCurrentVal {
//         roomState
//     }
// `

// const allRoomsQuery = gql`
//     query GetCurrentVal {
//         allRooms
//     }
// `

// const createRoomMutation = gql`
//     mutation CreateRoom($name: String) {
//         createRoom(name: $name){
//             id
//         }
//     }
// `

// const updateNameMutation = gql`
//     mutation createRoom {
//         {
//             id
//         }
//     }
// `

// export default function Home() {
//     const { data: initialData } = useQuery(query)
//     const { data, error } = useSubscription(sub)
//     const [incrementCounter] = useMutation(mut)
//     const {roomName, setRoomName} = useState('');

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to my counter!
//         </h1>
//           <h1 className={styles.title}>
//             Count: {data?.counterChanged || initialData?.counter}
//           </h1>
//           <Button onClick={() => createRoomMutation()}>Increment</Button>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
